-- usage: POSITRON_FOLDER $ sqlite3 scratch/database.db < scripts/sql/draft.sql

.headers on

--select ID, ID_WORKER, (PERFORMED_AT - START) as diffSTART, (DURATION - (FINISHED_AT - PERFORMED_AT)) as diffDuration
--from APPLICATIONS, WORKERS_APPLICATIONS 
--where ID = ID_APPLICATION AND DURATION != (FINISHED_AT - PERFORMED_AT) 
--order by ID;

-- select ID, ID_WORKER, (DURATION - (FINISHED_AT - PERFORMED_AT)) as diffDuration
-- from APPLICATIONS, WORKERS_APPLICATIONS 
-- where ID = ID_APPLICATION AND (DURATION - (FINISHED_AT - PERFORMED_AT) > 1) 
-- order by ID;

select ID, ID_WORKER, (PERFORMED_AT - START) as diffSTART
from APPLICATIONS, WORKERS_APPLICATIONS 
where ID = ID_APPLICATION AND ((PERFORMED_AT - START) > 0) 
order by ID;