-- usage: POSITRON_FOLDER $ sqlite3 scratch/database.db < scripts/sql/draft.sql

.headers on
.mode column

--select ID, ID_WORKER, (PERFORMED_AT - START) as diffSTART, (DURATION - (FINISHED_AT - PERFORMED_AT)) as diffDuration
--from APPLICATIONS, WORKERS_APPLICATIONS 
--where ID = ID_APPLICATION AND DURATION != (FINISHED_AT - PERFORMED_AT) 
--order by ID;

-- select ID, ID_WORKER, (DURATION - (FINISHED_AT - PERFORMED_AT)) as diffDuration
-- from APPLICATIONS, WORKERS_APPLICATIONS 
-- where ID = ID_APPLICATION AND (DURATION - (FINISHED_AT - PERFORMED_AT) > 1) 
-- order by ID;

-- select ID, ID_WORKER, (PERFORMED_AT - START) as diffSTART
-- from APPLICATIONS, WORKERS_APPLICATIONS 
-- where ID = ID_APPLICATION AND ((PERFORMED_AT - START) > 0) 
-- order by ID;

-- SELECT * 
-- from WORKERS, WORKERS_APPLICATIONS
-- WHERE WORKERS.ID = (
--     SELECT ID_WORKER 
--     from WORKERS_APPLICATIONS 
--     WHERE ID_APPLICATION = 179
--     );

-- SELECT * 
--     from WORKERS_APPLICATIONS 
--     WHERE ID_APPLICATION = 179 AND FINISHED_AT = 0;

UPDATE WORKERS_APPLICATIONS SET FINISHED_AT=102129.6 
WHERE ID_WORKER = 14 AND ID_APPLICATION = 179 AND FINISHED_AT = 0;

-- UPDATE APPLICATIONS SET FINISH = " << finish << " WHERE ID = " << application.ID << ";";